<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 25.04.2018
 * Time: 20:20
 */

namespace repository;


use model\Document;
use core\Repository;

class DocumentRepository extends Repository
{
    public function __construct()
    {
        parent::__construct("documents", Document::class);
    }

    public function  findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

}